apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "spegel.fullname" . }}
  labels:
    {{- include "spegel.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spegel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spegel.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spegel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- if .Values.spegel.containerdMirrorAdd }}
      initContainers:
      - name: configuration
        image: "{{ include "spegel.image" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        args:
          - configuration
          - --containerd-registry-config-path={{ .Values.spegel.containerdRegistryConfigPath }}
          {{- with .Values.spegel.registries }}
          - --registries
          {{- range . }}
          - {{ . | quote }}
          {{- end }}
          {{- end }}
          - --mirror-registries
          - http://127.0.0.1:{{ .Values.service.registry.hostPort }}
          - http://127.0.0.1:{{ .Values.service.registry.nodePort }}
          {{- with .Values.spegel.additionalMirrorRegistries }}
          {{- range . }}
          - {{ . | quote }}
          {{- end }}
          {{- end }}
        volumeMounts:
          - name: containerd-config
            mountPath: {{ .Values.spegel.containerdRegistryConfigPath }}
      {{- end }}
      containers:
      - name: registry
        image: "{{ include "spegel.image" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        args:
          - registry
          - --mirror-resolve-retries={{ .Values.spegel.mirrorResolveRetries }}
          - --mirror-resolve-timeout={{ .Values.spegel.mirrorResolveTimeout }}
          - --registry-addr=:{{ .Values.service.registry.port }}
          - --router-addr=:{{ .Values.service.router.port }}
          - --metrics-addr=:{{ .Values.service.metrics.port }}
          {{- with .Values.spegel.registries }}
          - --registries
          {{- range . }}
          - {{ . | quote }}
          {{- end }}
          {{- end }}
          - --containerd-sock={{ .Values.spegel.containerdSock }}
          - --containerd-namespace={{ .Values.spegel.containerdNamespace }}
          {{- with .Values.spegel.kubeconfigPath }}
          - --kubeconfig-path={{ . }}
          {{- end }}
          - --leader-election-namespace={{ .Release.Namespace }}
          - --leader-election-name={{ .Release.Namespace }}-leader-election
        ports:
          - name: registry
            containerPort: {{ .Values.service.registry.port }}
            hostIP: "127.0.0.1"    
            hostPort: {{ .Values.service.registry.hostPort }}
            protocol: TCP
          - name: router
            containerPort: {{ .Values.service.router.port }}
            protocol: TCP
          - name: metrics
            containerPort: {{ .Values.service.metrics.port }}
            protocol: TCP
        # Startup may take a bit longer on bootsrap as Pods need to find each other.
        # This is why the startup proben is a bit more forgiving, while hitting the endpoint more often.
        startupProbe:
          periodSeconds: 1
          failureThreshold: 60
          httpGet:
            path: /healthz
            port: registry
        readinessProbe:
          httpGet:
            path: /healthz
            port: registry
        volumeMounts:
          - name: containerd-sock
            mountPath: {{ .Values.spegel.containerdSock }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
        - name: containerd-sock
          hostPath:
            path: {{ .Values.spegel.containerdSock }}
        {{- if .Values.spegel.containerdMirrorAdd }}
        - name: containerd-config
          hostPath:
            path: {{ .Values.spegel.containerdRegistryConfigPath }}
            type: DirectoryOrCreate
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
